config/routes.rb
Rails.application.routes.draw do
  resources :wikis
  devise_for :users
  resources :charges, only: [:new, :create]
  post "charges/downgrade" => "charges#downgrade"

  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  
  belongs_to :user
  belongs_to :wiki


end

app/models/user.rb
class User < ApplicationRecord
  has_many :wikis
  has_many :collaborators
  has_many :collaborating_wikis, through: :collaborators, source: :wiki
  accepts_nested_attributes_for :collaborators

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :confirmable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  enum role: [:standard, :premium, :admin]
  after_initialize :set_default_role

  def set_default_role
    self.role ||= :standard
  end

  def self.default_amount
     1500
  end


end

app/models/wiki.rb
class Wiki < ApplicationRecord

  belongs_to :user
  has_many :collaborators
  has_many :collaborating_users, through: :collaborators, source: :user
  accepts_nested_attributes_for :collaborators

  validates :title, presence: true
  validates :body, presence: true


def self.public
  Wiki.where(private: false)
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  @stripe_btn_data = {
    key: "#{ Rails.configuration.stripe[:publishable_key] }",
    description: "BigMoney Mem@bership - #{current_user.email}",
    amount: User.default_amount
  }
end

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge

    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )



    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: User.default_amount,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )

    current_user.update_attribute(:role, "premium")

    flash[:notice] = "Thanks for all the money, #{current_user.email}! You now have access to private wikis!"

    redirect_to wikis_path(current_user) # or wherever

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def downgrade
    if current_user.role == "premium"
     current_user.update_attribute(:role, 'standard')
     current_user.wikis.where(private: true).update_all(private: false)
     flash[:notice] = "Sorry to see you go."
     redirect_to root_path(current_user)
   elsif current_user.role == "standard"
     flash[:notice] = "You are already a standard member"
     redirect_to wikis_path(current_user)
     end
   end


   #find sign_in in spec folder bloccit

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController


  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.collaborating_user_ids
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = current_user.wikis.build(wiki_params)
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.update_attributes(wiki_params)


    authorize @wiki
    if @wiki.update(wiki_params)
      redirect_to @wiki
    else
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      render "welcome/index"
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, { :collaborating_user_ids => [] })
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
    no_intra_emphasis: true,
    fenced_code_blocks: true,
    disable_indented_code_blocks: true,
    autolink: true,
    tables: true,
    underline: true,
    highlight: true
  )
  return markdown.render(text).html_safe
end

def form_group_tag(errors, &block)
  css_class = 'form-group'
  css_class << ' has-error' if errors.any?
  content_tag :div, capture(&block), class: css_class
end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
<% if current_user.role == "standard" %>
<h4>Private</h4>
<script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>
<% end %>
<% if current_user.role == "premium" %>
<h3>Downgrade to Techtannica Standard</h3>
<%= button_to "Downgrade", { :controller => "charges", :action => "downgrade"}, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade?'} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>techtannica</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">

</head>
<body>
  <nav class="navbar">
      <!-- <div id="navbar"> -->
        <ul class="nav navbar-nav">
    <li><%= link_to "Home", welcome_index_path, :class => "nav-link" %></li>
    <li><%= link_to "Wikis", wikis_path, :class => "nav-link"  %></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
    <li class="text-center signed-in">Signed in as: <%= current_user.email %></li>
    <li><%= link_to 'Edit profile', edit_user_registration_path, :class => "nav-link" %></li>
    <li><%= link_to "Sign Out", destroy_user_session_path, :class => "sign-out
    nav-link", method: :delete %></li>
    <% else %>
    <li><%= link_to "Sign In", new_user_session_path  %></li>
    <% end %>
  </ul>
<!-- </div> -->
</nav>
<div class="container">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
    <% end %>
    <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>techtannica</title>
    <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="nav"
      <p><%= link_to "Home", welcome_index_path, :class => 'navbar-link'  %></p>
    <% if user_signed_in? %>
  Signed in as: <strong><%= current_user.email %></strong> |
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <p><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %></p>
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
    <%= yield %>
  </div>
</div>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="row text-center">
  <div>
    <div class="dotted-border">
      <h1 class="hero">TECHTANNICA</h1>
      <h3 class="sub-hero">Social, Markdown Wikis.</h3>
      <% if user_signed_in? %>
      <br></br>
      <button type="button"><%= link_to "New", new_wiki_path  %></button>
      <button type="button"><%= link_to "Browse", wikis_path  %></button>
      <% else %>
      <button type="button"><%= link_to "Sign Up", new_user_registration_path  %></button>
      <% end %>
      <% if current_user.role != "premium" %>
      <button type="button"><%= link_to "Subscribe", new_charge_path  %></button>
      <% else %>
      <button type="button"><%= link_to "Unsubscribe", new_charge_path  %></button>
      <% end %>
      <br></br>
    </div>
  </div>
</div>

app/views/wikis/_form.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
    <% if @wiki.errors.any? %>
<div class="alert alert-danger">
  <h4><%= pluralize(@wiki.errors.count, "error") %></h4>
  <ul>
    <% @wiki.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
    <%= form_group_tag(@wiki.errors[:title]) do %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    <% end %>
    <%= form_group_tag(@wiki.errors[:body]) do %>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
    <% end %>
    <div class="col-md-8">
      <% if current_user.admin? || current_user.premium? && @wiki.user_id == current_user.id  %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private%> Private wiki
        <% end %>
      </div>
      <% end %>
      <div class="form-group">
        <% if @wiki.private == true %>
        <p>Add a Collaborator</p>
        <% collaborating_user_ids = @wiki.collaborating_user_ids %>
        <%= hidden_field_tag "wiki[collaborating_user_ids][]", nil %>
        <% User.all.each do |user| %>
        <div class="user">
          <%= check_box_tag "wiki[collaborating_user_ids][]", user.id, collaborating_user_ids.include?(user.id) %>
          <%= user.email %>
        </div>
        <% end %>
      </div>
      <% end %>
      <div class="form-group">
        <button><%= f.submit "Save"%></button>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<%= render 'form' %>

app/views/wikis/index.html.erb
<h1>Wikis</h1>
<% @wikis.each do |wiki| %>
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to wiki.title, wiki_path(wiki.id) %>
    </h4>
  </div>
</div>
<% end %>
<br></br>
<button type="button"><%= link_to "New Wiki", new_wiki_path  %></button>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">

  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
    </div>
    <div class="col-md-8">
      <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private%> Private wiki
        <% end %>
      </div>
      <% end %>
      <div class="form-group">
        <button><%= f.submit "Save" %></button>
      </div>
      <% end %>
    </div>
  </div>

app/views/wikis/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= markdown(@wiki.title) %>
    <%= markdown(@wiki.body) %>
  </div>
</div>
<br></br>
<div class="row">
  <div class="col-md-8">
    <button><%= link_to "Edit", edit_wiki_path(@wiki) %></button>
    <button><%= link_to "Delete", @wiki, method: :delete, data: {confirm: 'Are you sure you want to delete this wiki?'} %></button>
  </div>
</div>
<hr></hr>
<div class= "row">
  <div class="col-md-8 user">
    <% if @collaborators.count >= 1 %>
    <h3><%="Collaborators"%></h3>
    <% end %>
    <%= hidden_field_tag "wiki[collaborating_user_ids][]", nil %>
    <% collaborating_user_ids = @wiki.collaborating_user_ids %>
    <% User.all.each do |user| %>
    <% if collaborating_user_ids.include?(user.id) %>
    <p><%= user.email %></p>
    <% end %>
    <% end %>
    <br></br>
    <%= link_to "back", wikis_path %>
  </div>
</div>
</div>